### ISSUE TITLE
Unable to fetch zip links for folders 

### ISSUE THREAD

**Issue by tekeayush** [Mr-Developer-X/SeedrClient#1]
![image](https://github.com/user-attachments/assets/6b4ecf49-10bd-43b1-8e5a-466026b263d3)

```
from seedr_client import SeedrHandler
seedr = SeedrHandler(email=mail, password=password)
folder_id = seedr.get_drive()['folders'][0]['folder_id']
print(seedr.download_folder(folder_id, builtin_downloader=False))
```

this is the code i am using, please let me know if there is any solution for it

**Comment by Mr-Developer-X** [comment]
This is not possible because of how Seedr manages zip files, which is it extracts the zip and provides you with a folder with the same name. That is why I made an option to recursively download all files. Check the documentation for how to download a folder(this is the same as downloading the zip file, but uncompressed, if you want you can compress it again after this step).
Check how to do it [here](https://seedrclient.readthedocs.io/en/latest/seedr_client.html#seedr_client.SeedrHandler.download_folder).

Hope that helps you. If you have any other issues let me know. And if you like the repo, please be sure to give it a star

**Comment by tekeayush** [comment]
I found the solution to fetch the zip links for folder

```
    def zip_folder(self, folder_id):
        client = requests.session()
        client.cookies.set('RSESS_remember', self.rsess_remember)
        data = {
    'archive_arr[0][type]': 'folder',
    'archive_arr[0][id]': folder_id
        }
        generated_uuid = str(uuid.uuid4())
        try:
            resp = client.put(self.zip_link+generated_uuid, data=data)
            if resp.json()['success'] == True:
                return resp.json()['url']
            else:
                return (f'Error @Zip_folder: {resp.text}')
        except Exception as e:
            return (e.__class__.__name__, f"{e}")
        
```

![image](https://github.com/user-attachments/assets/1099f8bb-57d6-4b42-894b-e6d15cbff4bf)
